version: "3.3"
services:
  ceph-salt:
    build:
      context: ..
      dockerfile: ./Docker/ceph-salt-master.Dockerfile
    volumes:
      - ../:/ceph-salt:ro
    entrypoint: ./Docker/entrypoint.sh
    hostname: salt # Minion is looking for host `salt` by default
